spring:
  # .env import
  config:
    import: optional:file:.env[.properties]

  application:
    name: shop

  # database connection
  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # S3 setting
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET}


# server setting
server:
  servlet:
    session:
      timeout: 3600s
      cookie:
        max-age: 3600s