name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ShoppingMall
          environment_name: test-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: ./build/libs/${{env.artifact}}

      - name: Update Elastic Beanstalk Environment Variables
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ShoppingMall \
            --environment-name test-env \
            --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_URL,Value=${{ secrets.DB_URL }} \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_ID,Value=${{ secrets.DB_ID }} \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_PW,Value=${{ secrets.DB_PW }} \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=S3_ACCESS_KEY,Value=${{ secrets.S3_ACCESS_KEY }} \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=S3_SECRET_KEY,Value=${{ secrets.S3_SECRET_KEY }} \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=S3_BUCKET,Value=${{ secrets.S3_BUCKET }} \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=JWT_SECRET_KEY,Value=${{ secrets.JWT_SECRET_KEY }}